version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.35.0
    - 5.35.1
  - dependency-name: socket.io-client
    versions:
    - 4.0.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
  - dependency-name: css-loader
    versions:
    - 5.0.2
  - dependency-name: lint-staged
    versions:
    - 10.5.4
  - dependency-name: "@babel/core"
    versions:
    - 7.13.8
