services:
    - docker

env:
  global:
    - IMAGE_NAME=namelivia/flappysonic

before_script:
  - docker pull "$IMAGE_NAME" || true

script:
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .

before_deploy:
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
